version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/data/postgres
volumes:
  postgres-db:
    driver: local